//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.10 at 09:20:50 AM EEST 
//


package ro.infrasoft.ws.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CautareDosare2Result" type="{portalquery.just.ro}ArrayOfDosar" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cautareDosare2Result"
})
@XmlRootElement(name = "CautareDosare2Response")
public class CautareDosare2Response {

    @XmlElement(name = "CautareDosare2Result")
    protected ArrayOfDosar cautareDosare2Result;

    /**
     * Gets the value of the cautareDosare2Result property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDosar }
     *     
     */
    public ArrayOfDosar getCautareDosare2Result() {
        return cautareDosare2Result;
    }

    /**
     * Sets the value of the cautareDosare2Result property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDosar }
     *     
     */
    public void setCautareDosare2Result(ArrayOfDosar value) {
        this.cautareDosare2Result = value;
    }

}
