//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.10 at 09:20:50 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "portalquery.just.ro", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.infrasoft.ws.dto;
